<?php
$user_profile = $this->user_profile;
?>

<div class="row-fluid">

 <div class="span12">
  <a href="#" onclick="document.getElementById('directories').style.display='block'; return false; ">Directories</a>

  <div id="directories" style="display: none;">
   <a href="https://jbaron6.cs2212.ca/test"><h3>Test Project</h3></a>
   <a href="https://jbaron6.cs2212.ca/jamesb"><h3>James Baron</h3></a>
   <a href="https://jbaron6.cs2212.ca/jamesa"><h3>James Anderson</h3></a>
   <a href="https://jbaron6.cs2212.ca/yaqzan"><h3>Yaqzan</h3></a>
   <a href="https://jbaron6.cs2212.ca/frank"><h3>Frank</h3></a>
   <a href="https://jbaron6.cs2212.ca/taylor"><h3>Taylor</h3></a>
  </div>

 </div>

 <div class="span12">

  <div style="text-align: center">
   <div id="intro">
    <img onclick="window.open('<?php echo $user_profile['link']; ?>', '_blank')"
         src="https://graph.facebook.com/<?php echo $user_profile['id']; ?>/picture">

    <h1>Welcome, <?php echo $user_profile['first_name']; ?>!</h1>
    <br/>


    <applet code="gui.TTApplet.class" width=802, height=600 codebase="https://jbaron6.cs2212.ca/ttableapplet/home" archive="json-simple-1.1.1.jar"></applet>

    <!--<applet code="gui.TTApplet.class" width=800, height=600 codebase="https://jbaron6.cs2212.ca/ttableapplet" archive="json-simple-1.1.1.jar"></applet>-->

   </div>


  </div>
 </div>

</div>