<?php
$fb_id = $this->fb_id;
$user_profile = $this->user_profile;
?>


<div style="text-align: center">
 <div id="intro">
  <img onclick="window.open('<?php echo $user_profile['link']; ?>', '_blank')" src="https://graph.facebook.com/<?php echo $user_profile['id']; ?>/picture">

  <h1>Welcome, <?php echo $user_profile['first_name']; ?>!</h1>
  <br/>


  <applet code="gui.TTApplet.class" width=802, height=600 codebase="https://jbaron6.cs2212.ca/ttableapplet/yz" archive="json-simple-1.1.1.jar"></applet>
  

 </div>


</div>

<a href="https://jbaron6.cs2212.ca/test"><h3>Test Project</h3></a>
